spring:
  cloud:

#    sentinel:
#      transport:
#        #配置sentinel dashboard地址
#        dashboard: localhost:8080

    gateway:
      routes:
        - id: product_route
          uri: lb://yunmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: coupon_route
          uri: lb://yunmall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: third_party_route
          uri: lb://yunmall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*),/$\{segment}

        - id: member_route
          uri: lb://yunmall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: ware_route
          uri: lb://yunmall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: order_route
          uri: lb://yunmall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}

        - id: yunmall_host_route
          uri: lb://yunmall-product
          predicates:
            - Host=yunmall.com,item.yunmall.com

        - id: yunmall_search_route
          uri: lb://yunmall-search
          predicates:
            - Host=search.yunmall.com

        - id: yunmall_auth_route
          uri: lb://yunmall-auth-server
          predicates:
            - Host=auth.yunmall.com

        - id: yunmall_cart_route
          uri: lb://yunmall-cart
          predicates:
            - Host=cart.yunmall.com

        - id: yunmall_order_route
          uri: lb://yunmall-order
          predicates:
            - Host=order.yunmall.com

        - id: yunmall_member_route
          uri: lb://yunmall-member
          predicates:
            - Host=member.yunmall.com

        - id: yunmall_seckill_route
          uri: lb://yunmall-seckill
          predicates:
            - Host=seckill.yunmall.com



#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
