server:
  port: 10000

spring:
  application:
    name: yunmall-product
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/yunmall_pms?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  # 设置 xml 文件扫描路径
  mapper-locations: classpath:/mapper/**/*.xml
  # 设置实体类的自增主键
  global-config:
    db-config:
      id-type: auto
      # 逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0
